### ISSUE TITLE
Custom easing

### ISSUE THREAD

**Issue by sergavshin** [davidcetinkaya/embla-carousel#184]
### Feature request is related to

- [ ] The Vanilla JavaScript version
- [ ] The React version
- [x] The Embla Carousel core (all versions)
- [ ] Documentation website
- [ ] Other

Hi. Thanks for the library. Have you any plans to support custom easing?

**Comment by davidcetinkaya** [comment]
Hi Sergey (@sergavshin),

> Have you any plans to support custom easing?

Thank you for your question. No, I haven't considered it. Let's take a simple easing function as an example:

```js
function easeInSine(x: number): number {
  return 1 - cos((x * PI) / 2);
} 
```

**Easing** functions specify the rate of change of a parameter over time. However, it doesn't take mass and other variables needed for an attraction force simulation into account. This is what Embla Carousel does. It animates with a simple physics simulation that simulates attraction force. Maybe there is a way to add variables like mass to an easing function, but at the time of writing, I don't know how to achieve this.

**Comment by Angelizo1** [comment]
Hello,

I actually want to slow down the transition from slide to slide in my React app. I am glad I found this issue about Custom easing, but now I am wondering how to implement it in my carousel since I feel the speed at which my slides transition from one to another is just to fast. I am new to programming, so sorry If I do not see the obvious considering you guys did not continue elaborating on this issue further down. Also I tried to read through the documentation but the only option I see is delay, but that's used for how long each slide is currently shown. 

Anyways, thanks in advance. Any help is much appreciated.

**Comment by davidjerleke** [comment]
@Angelizo1 the [speed option](https://www.embla-carousel.com/api/options/#speed) should be what you’re looking for.

Best,
David

**Comment by SunpieAgency** [comment]
Hi,

i'm facing an issue with the slide transition on screens with higher refresh rates such as iPad Pro (120 Hz):
It seems like the way the transition is done (changing values of the translate3d property using inline CSS) is causing studdering. The transition is not as smooth compared to a "real" CSS transition, with a starting and an end point where all the motion inbetween is done dynamically.

I get the point of attraction force. But isn't there a way to simulate it with things like transition time and transition-timing-function (cubic-bezier)?

This is actually the only fly in the ointment. Thank you!

**Comment by davidjerleke** [comment]
Hi @SunpieAgency,

This is on the roadmap and the problem is caused by the animation not being frame rate agnostic. There’s already a bug report for this:

#387 

Best
David

**Comment by SunpieAgency** [comment]
Hi @davidjerleke,

thank you for your quick response. I have read that topic but i'm not really facing differences in animation speed. It's just studdering on 120 Hz. Are those two issues going hand in hand?

I was just wondering if inline CSS animations could ever be as smooth as normal CSS transitions?

Thank you!

**Comment by davidjerleke** [comment]
- @SunpieAgency I'll let you know when I have a draft for: #387 that you can try out.

**Comment by davidjerleke** [comment]
Hi @SunpieAgency,

Would you mind testing [this CodeSandbox](https://s81z1o.csb.app/) on:

- Your regular devices where you didn't experience the stuttering.
- And also your iPad Pro with a higher frame rate (120 Hz) where Embla is stuttering.

?

⚠️ **Note:** The CodeSandbox is not Embla Carousel. It's just a red square that's animated across the screen. The **total runtime** for all devices should be something around `1500` milliseconds (give and take 30 milliseconds), no matter the refresh rate. Also note that the runtime won't be exactly 1500 and may slightly vary from one try to another. If that's the case, I will continue and implement this into the Embla Carousel core.

Thanks in advance!
David

**Comment by SunpieAgency** [comment]
Hi @davidjerleke,

sure! I got around 1500ms on each device. :)

Thank you!

**Comment by davidjerleke** [comment]
Thanks @SunpieAgency! And I’m assuming that both were smooth? Even 120Hz?

**Comment by davidjerleke** [comment]
Hi @SunpieAgency,

Thanks for explaining further. Would you mind attaching a screen recording where you animate both, one at a time?

I noticed that the CSS easing isn’t the same as the Javascript example. Please use `easeOutQuint` from here:

https://easings.net/#easeOutQuint

**Comment by SunpieAgency** [comment]
@davidjerleke,
thank you, I changed the transition-timing-function.

Well, my iPad screenrecords at 45fps. I cannot face any differences in a 45fps video file. I guess you would need to watch it on a 120Hz screen, recorded on 120fps which on the other hand is needless because then you could just check the codebox itself :)

Don't you have access to a higher framerate display?

Thanks for your effort!

**Comment by davidjerleke** [comment]
@SunpieAgency have you tried turning on the paint flash indicator in Chrome and added backface-visibility: hidden; to the red square or similar to make sure the example animation isn’t triggering any paint?

**Comment by davidjerleke** [comment]
@SunpieAgency never mind my last comment! I will update the CodeSandbox for you and you can try on a 120Hz monitor again to see if the stuttering goes away or not. I will let you know when I’ve updated the CodeSandbox.

**Comment by SunpieAgency** [comment]
Okay, thank you @davidjerleke

Anyway, no paint ;)

**Comment by davidjerleke** [comment]
Hi @SunpieAgency,

Paint **was flashing** on when I tried the sandbox so there was a little room for improvement 🙂. Please try [this CodeSandbox](https://punyly.csb.app/) on **120Hz** and let me know if the "stuttering" is still happening. 

Thanks for your time!
David

**Comment by SunpieAgency** [comment]
Hi @davidjerleke,

as far as I can judge, and I watched it about 100 times now, it is pretty much perfect. In any case better than your previous Sandbox.

I think - if anything - I can see a minimal difference in terms of smoothnes in the speeding up part (first half). But I'm not sure about that. Maybe I have to watch it again tomorow 😅

**Comment by davidjerleke** [comment]
@SunpieAgency thanks for testing it out. Haha yeah, eyes can get crazy from watching the same thing over and over 😅. So if I understand you correctly, the "stuttering" thing is gone on the JavaScript animation?

Cheers,
David

**Comment by SunpieAgency** [comment]
@davidjerleke, thanks for your great efforts.

It is far away from stuttering now but as I mentioned, i'm not sure if it is 100% as smooth as a pure CSS transition. At least I'm not safe to say there are differences. So _if_ there are, they are negligible I'd say ;)

**Comment by davidjerleke** [comment]
@SunpieAgency that's great news then 🎉 . Thanks again! I think there might be a slight (barely noticeable) performance advantage to CSS transitions in general, but JavaScript gives you more control over exact current position and similar, which is very useful for this carousel. 

I'll let you know when I have a working Embla draft that is frame rate agnostic.

Best,
David

**Comment by SunpieAgency** [comment]
@davidjerleke I guess v8.0 fixes this? :)

**Comment by davidjerleke** [comment]
Hi @SunpieAgency,

The latest release is frame rate independent but I have one small fix left which will be released with v8.0.0-rc03 soon. It will be smoother after that release.

Best,
David

**Comment by davidjerleke** [comment]
@SunpieAgency I've released [v8.0.0-rc03](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc03) now. Feel free to try it out. **Note** the following:

### Embla is now frame rate independent
The animation **durations** will be the same whether your screen has a refresh rate of 30Hz, 60Hz, 120Hz or anything else.

### Smoother animations
Sometimes you get smoother animations if you promote the element that will be animated to its own layer. In the case of Embla it's the container. There are a **lot of ways** to do this and the internet is full of suggestions so please read about them. You can try different approaches and see if any of the suggested solutions improves the animation smoothness. For example:

**HTML**
```html
<div class="embla__container">
  ...slides go here
</div>
```

**CSS**
```css
.embla__container {
  will-change: transform;
}
```

...or:

```css
.embla__container {
  backface-visibility: hidden;
}
```

...or

```css
.embla__container {
  transform: translateZ(0);
}
```

**Comment by SunpieAgency** [comment]
Hi @davidjerleke,

Thank you! I found time to test it now. 

I'm afraid to tell that I'm still facing some (heavy) stuttering (tested on different 120hz screens and different carousels - also the ones provided in your examples). Maybe it's deceptive but it seems to me that it does not happen on every single scoll (still most of the time) and mostly on carousels with multiple slides in view (e.g. https://codesandbox.io/s/wz8mem).

Anyway, thanks for your effort. Embla is still the best option for me :)

**Comment by SunpieAgency** [comment]
Well, I found out there is a relation between stuttering and my implemantation of lazy img loading. It's pretty smooth without :) Nevermind my last post, I'm happy ;)

Thank you!

**Comment by davidjerleke** [comment]
Hi @SunpieAgency,

> It also seems to happen mostly on the first "run". As soon as each slide was scrolled at least once it appears much smoother.

Actually, I also noticed this but when I started investigating it I got more and more confused.

When I measured the time it takes for all update logic that drives the animation for a single frame, it never exceeded 1ms. And Embla animates with a controlled frame rate of 60fps, which means that there’s 16.666ms between each frame. This means that the CPU is never struggling when Embla runs its animation code for each frame. So too heavy calculations shouldn’t be the culprit.

I tried enabling paint flash in Chrome dev tools and found green flashing (paint flash). I added layer promoting CSS to the slides and the container and most of the paint flashing went away, but there were still something flashing that I couldn’t narrow down. This is weird because the only thing Embla does is that it animates using translate3d which shouldn’t trigger paint. Maybe this is the culprit but as I said I couldn’t understand where the paint flashing was happening (on which element).

I’ve also tried animating with integers only (not floating points) but to no avail. It didn’t improve anything.

Give it a go if you want to investigate this further. I would like to know why this is happening and any help would be greatly appreciated 👍🏻.

Best,
David

**Comment by SunpieAgency** [comment]
Sure, I'm happy to do anything to improve this good piece of work 🙂

**Comment by davidjerleke** [comment]
Thanks a lot @SunpieAgency. Let me know how it goes 👍.

**Comment by SunpieAgency** [comment]
@davidjerleke,
So what can I do? :)

Additionally I noticed another strange kind of "wiggling" on Firefox which is visible on 60hz as well.

**Comment by davidjerleke** [comment]
@SunpieAgency I'm not sure 😕. As I mentioned in my [previous comment](https://github.com/davidjerleke/embla-carousel/issues/184#issuecomment-1538448863), this is what I have tried to investigate so far. I said this:

> Give it a go if you want to investigate this further.

...because I don't know where to go from here. I guess I meant that if you find any articles/questions online about `translate3d()` with JavaScript that stutter, or `requestAnimationFrame` is choppy or similar, please share. Or anything else that might be of use in this case.


### One thing I have noticed:

I don't get stutter until the CPU is a bit busy. As soon as the CPU load is moderate --> high (from 20% and up), I can see a little bit of stuttering but not much. You could try to close any other tabs or piece of software that is running on your machine to make sure the CPU load is very low. Let me know if you intend to test this and your findings.

If this is the case for you too, it might be the case that browsers are throttling `requestAnimationFrame` when the CPU load goes up. And I'm not sure if browsers throttle CSS animations in the same way. Maybe CSS animations are excluded from the CPU throttling behaviour? Don't know.

Best,
David

**Comment by SunpieAgency** [comment]
Hi @davidjerleke,

I have tried several times to identify the problem more precisely, but not really successfully. Sorry for the late reply anyway.

What I did find on the subject though:

> Inline styles and changing the translate value in short intervals can be used to achieve animated effects, but this may not be as efficient as CSS transitions or CSS animations optimized by modern browsers.
> 
> CSS Transitions use the GPU of the device to perform the animations in a hardware accelerated way. This allows for smooth and optimized animations. If you use inline styles, the GPU optimization may not be used, which can result in lower performance.

Whether that is true in this case is another question. I can't really contribute much to this topic, unfortunately, except to say that I can see a difference on the different devices. This could be an issue after the refresh rate tends to increase in the future.

Have you looked into it any further?

Thank you

**Comment by davidjerleke** [comment]
Hi @SunpieAgency,

Thank you for investigating this further.

> Inline styles and changing the translate value in short intervals may not be as efficient as CSS transitions or CSS animations optimized by modern browsers

Yes. As I mentioned in one of my previous comments browsers are throttling `requestAnimationFrame` when the CPU load goes up.

Additionally, browsers (or devices?) handle hardware acceleration differently which is really annoying. Embla is using translate3d which should hardware accelerate the animation but some browsers also need CSS hacks to actually promote it to a separate layer and optimize the layer (for example: `will-change: transform;`).

In contrast, I think CSS animations are excluded from the CPU throttling behaviour.

> This could be an issue after the refresh rate tends to increase in the future.

I don’t think this is related to the refresh rate at all, but rather to the device. At least to some extent. Because I have a more modern MacBook where I never see any stuttering, literally never regardless of CPU load. Not in any browser whether I use Chrome, Safari or Firefox.

In contrast, I have an older model where it doesn’t stutter but as soon as the CPU load goes up a bit, it starts to stutter occasionally.

I haven’t seen a screen recording demonstrating the stuttering you mention so I don’t know what I’m working with here 😕.

If you want to try some stuff, you could go through [this discussion](https://github.com/nolimits4web/swiper/issues/3527#issue-comment-box) and see if any of the CSS hack solutions mentioned there makes any difference.

Best,
David

**Comment by SunpieAgency** [comment]
Hi @davidjerleke,

I noticed the flickering on my 120Hz iPad Pro (but not on my 60Hz iPhone). So I thought it was related to the refresh rate.

I'll let you know as soon as I found out something new. Thanks for the link and for your help!

**Comment by 9mm** [comment]
@davidjerleke I understand what you mean about animation and such now... but would you ever consider adding more parameterizations like flickity has?

ie:

* selectedAttraction
* friction
* freeScrollFriction

https://flickity.metafizzy.co/options#selectedattraction-friction

**Comment by 9mm** [comment]
Nevermind, I found this:

https://github.com/davidjerleke/embla-carousel/issues/483#issuecomment-1563955459

**Comment by davidjerleke** [comment]
@SunpieAgency would you mind testing this [CodeSandbox](https://ntyl6q.csb.app/) on your `120Hz iPad Pro` and on your `60Hz iPhone` to see if the animation is smooth on both your devices?

**Comment by Monstass** [comment]
Hi @davidjerleke,

While it works really well in opera, it feels kinda choppy in chrome and firefox on my phone.

Used Pixel 9 Pro XL, android 16, tried to use forced peak refreshrate in development settings but no luck. On my pc with 144hz i have no issues.

Do you have any insight about that?

Thanks for your work.

**Comment by davidjerleke** [comment]
Hi @Monstass,

Thanks for sharing the details. Unfortunately, I can’t properly test this myself since I only have access to different versions of iPhones, and BrowserStack already adds a lot of lag so I can’t rely on it to test performance accurately.

If you can provide a **CodeSandbox** with the setup that’s causing the lag, I can at least go through the code and check for potential performance issues.
